a = int(input('Nhap so thu nhat: '))
b = int(input('Nhap so thu hai: '))
print('Tong: ', a + b)
print('Hieu: ', a - b)
print('Tich: ', a * b)
print('Thuong: ', a / b if b != 0 else 'Khong the chia cho b')